language: objective-c
osx_image: xcode10.2
xcode_workspace: YandexCheckoutShowcaseApi.xcworkspace
xcode_scheme: YCShowcaseApiExamplePods
cache:
  bundler: true
  cocoapods: true
  directories:
  - Carthage
notifications:
  slack:
    secure: XA9veAJBA1IRe1DEdgGQI/I0UP/D50/L2D9UafVfvvYQllAXsDl9smhwE6FVuvy+bCJWNnY9goBsRHfQbA7Kex2BnEOKRuEA/zeh7byNIfgQejGpkLP37+rlma7USR5egCyqdGWA1qLxj9/en1znebGdGXIK1n2wioTuF/M21yCArBSjTCdudicCyUWw8mInFu5rRL2laOTN8YGB75hRl+AQcFtuI8pRPHaY/3uqN9AFYq5KAfzRwjvKpA+OM0AIlnM+lwDeQrgZFbNNPRZ2HKO7KUSwt767fkUi48gCof7TYFfPtcES8LoUUrvqSp/WTIysSY/naGHSdIqsW/SeNzlUjayafBWyJkdozy5TPlRjrVFYo6qOD9NWAdR+aBmnNfi13GbFsV3KzRYuccOADdbIBjVmpbh5zwTdf6mhfIwnweuj2WPKk5xbrHx4ik0SHr0j5Z49kp0pQg0nBr7ajmRGhQK5fPj8NVxfWOJlvVkBQPcfgd8awo7wqge5ZzuSntKiGciz8pOrW1j3LMvaRR99+101YBwAILZDczBJvxWBmfFioo9wMMFjf4YgRqIpkLZCe8TcjLd9p/1AwS5LQ0tmtV0dpILUt6J0OB9PMNMWfBSwUQcEpogWA1ou+5zCkTO7rN5QxqBvdJD3wczxzfPn0vd/ABr+KsX05J4/Sqc=
before_install:
- brew update && brew bundle
- bundle install --jobs=3 --retry=3 --deployment
- pushd .
- bundle exec pod repo update
- bundle exec pod install
install: true
before_script:
- carthage bootstrap --platform iOS --cache-builds
script:
- swiftlint
- bundle exec fastlane build
- bundle exec fastlane scan
