language: objective-c
osx_image: xcode9.2
xcode_workspace: YandexCheckoutShowcaseApi.xcworkspace
xcode_scheme: YCShowcaseApiExamplePods
cache:
  bundler: true
  cocoapods: true
  directories:
  - Carthage
notifications:
  slack:
    secure: vO6AOLb10p2BciTCjJg9cOupHSSF2GDXg0BEL1RyLh+IcSozDMFqb97HizFdZGoSIXkAqgi/NYmVF3sPAXGEb6EfjETm+ys3nqssxWFihuA7FzY8n8xfmAfZBDgrGXD0qgG1ZmzDtBcOBor4BguD1NH9jVqGNI5mlcGQKuls8JbasXQZMC0m9CEFyPfruoPk/ECoH+TsBjF3RA4x8CAmKVGpCo7pMqRZ2iRnHj03P9VhGvyyA2EqVSwvW+3h0RUnIpcXMMmP1YPf2eWK+WgcE1RWT1P4qP/MSNClLoncPPtf+zTlPvtJ12mflG651a+8a98j8zMU2Ft+44YLOM/D5ZQ9pnewAx+WezRp5TVhzypDwfUxz/qJMwh+xsYl9sLQgJ3tr7NiTdstsA26YETJ/Ev6Fd7zDCYV/L7JObzHZjKSTWRGHsHlz+lxCUYwbnmIPWT1XtT6S+ysfidaUgNdnJVJ+m4wL9/ewPY+IAw890tRy45aDxUAkj56/l6ApdwZhOHn4nCMi2ims4IWM75F9BOAlLmW2novt/m4UNKzorCf4MjmiUMR6h1BEn9pOsTUL0RW/bOHAR+D1RShi+1vKQW4n8vD4D38R3gMGtXoWpXbgIPN5KUvUVh1GQ/oZNs0L7z/KRhfsQXzmbzgVnBWBbiIoLu+GuQWQ46icI0ljeQ=
before_install:
- brew update && brew bundle
- bundle install --jobs=3 --retry=3 --deployment
- pushd .
- bundle exec pod repo update
- bundle exec pod install
install: true
before_script:
- carthage bootstrap --platform iOS --cache-builds
script:
- swiftlint
- bundle exec fastlane build
- bundle exec fastlane scan
